### ISSUE TITLE
clamdscan exits with status code 127

### ISSUE THREAD

**Issue by lithiumoxide** [widdix/aws-s3-virusscan#45]
Hi,

I deployed the solution earlier today. When I upload an EICAR test file, I can see the SQS message in the ScanQueue queue. However, it remains "in flight".

I checked /var/log/messages and I found:

`Jan 16 15:02:52 ip-10-100-3-65 s3-virusscan[3065]: message failed: #<RuntimeError: s3://bucketnamehere/file3 could not be scanned, clamdscan exit status was 127, retry>`

Any ideas?

**Comment by lithiumoxide** [comment]
Hi,

No, I viewed the messages file in CloudWatch Logs. I didn't deploy the template with SSH access but I'll try to change that now.

**Comment by lithiumoxide** [comment]
Looks like clamdscan isn't present:

```
[ec2-user@ip-10-100-38-224 ~]$ clamdscan /tmp/hi.txt
-bash: clamdscan: command not found
```

**Comment by michaelwittig** [comment]
I released a new version. Can you check if this works for you?

**Comment by lithiumoxide** [comment]
That works! Thanks very much! Looking forward to using this solution.

**Comment by RamblingRambo** [comment]
@michaelwittig I am having the same issue with an installation that has been working fine for 6 months, then when autoscaling replaced an unhealthy instance this error has been occuring. I can also see 
bash: clamdscan: command not found

How do i perform an update without using the cloudformation script?

**Comment by michaelwittig** [comment]
The only supported way is to use the CloudFormation template.

**Comment by lmf66** [comment]
@michaelwittig We are running into the same issue - initial deployment was months ago with everything working fine.  As of the last autoscale, the new ec2 instance is throwing the same error:  clamdscan: command not found with error code 127.

Is it possible to fix this on our current deployments/ec2 instances without updating our cloudformation template?  Would we be able to do a yum update or config update for clam.d-conf for example?

What is the root cause of the new autoscaled instances not finding clamd?

Thanks in advance for your advice.
