### ISSUE TITLE
Move Infected File

### ISSUE THREAD

**Issue by slynch401k** [widdix/aws-s3-virusscan#52]
Thank you for your hard work and time.  I have been coding for a few years now and understand how much time and thought things take.

One thing, is there a way to move infected files to a specific folder?

**Comment by michaelwittig** [comment]
No, moving is not supported. We can remove or tag an infected file.

You could add this functionality here: https://github.com/widdix/aws-s3-virusscan/blob/master/template.yaml#L737
Keep in mind that S3 does not support a move command. You have to copy the file and remove the old one. Make sure that this does not trigger another virus scan run, otherwise you end up with an expensive infinite loop :)

**Comment by slynch401k** [comment]
Thank you Michael.
