### ISSUE TITLE
How to Look at Logs Showing Deleted Files

### ISSUE THREAD

**Issue by slynch401k** [widdix/aws-s3-virusscan#53]

**Comment by slynch401k** [comment]
I'm not sure how to view these. I went to Go to CloudWatch Logs in the AWS Management Console
Click on the log group of the s3-virusscan
Click on the blue Search Log Group button
Search for "s3-virusscan["

But when I search nothing comes up.

**Comment by michaelwittig** [comment]
does it show some data if you search for nothing?

**Comment by j1mmie** [comment]
Ran into a similar problem. When I searched, nothing came up:

![image](https://user-images.githubusercontent.com/4650220/61916073-eb58cb00-aefb-11e9-8acc-dcb6de97a3be.png)

I determined it was because the ruby script was executing `log.debug` instead of `log.info` for the relevant lines:

https://github.com/widdix/aws-s3-virusscan/blob/master/template.yaml#L707

I forked the project and changed them to `log.info` lines. I also rearranged them so that the log lines get executed regardless of the reporting options. IMO the SNS reporting configuration should be separate from logging. In my case, I want to log every scan, every result, etc.:

https://github.com/Reflektive/aws-s3-virusscan/blob/master/template.yaml#L722

![image](https://user-images.githubusercontent.com/4650220/61916766-aa15ea80-aefe-11e9-89f7-a359b04ff695.png)

Much better

template.yaml file located here on S3. Hope this is helpful:

https://reflektive-s3-virusscan.s3-us-west-1.amazonaws.com/template.yaml

**Comment by michaelwittig** [comment]
the best way to get notified about deleted files is be subscribing to the findings sns topic.
The problem with logging is that the log file can grow big
