### ISSUE TITLE
Feature: Create a parameter to control key associated with kms:Decrypt action

### ISSUE THREAD

**Issue by ulziibay** [widdix/aws-s3-virusscan#85]
AWS Marketplace customers have access to support via email: hello@widdix.net

Hello, I am with Clever's Security team and we are adopting your virus scan. It would be great if I can control the key associated with kms:Decrypt as a parameter to the CF Template file. This ensures the principle of least privilege for us. Let me know your thoughts on the issue or at security@clever.com. Thank you.

**Comment by michaelwittig** [comment]
Hi @ulziibay 
Just to make sure that I understand your requirement. Are you asking for a parameter to control this `*` https://github.com/widdix/aws-s3-virusscan/blob/master/template.yaml#L385?

**Comment by ulziibay** [comment]
@michaelwittig exactly right! As is, this is too broad due to `*`

**Comment by ulziibay** [comment]
In general, if you can clarify why kms:decrypt action is needed for the `s3read` policy, that would be great!

**Comment by michaelwittig** [comment]
The action is needed to download KMS encrypted files from S3 (together with a KMS key policy that allows the IAM role to do so).

You can configure this option in our commercial offering: https://bucketav.com/

Otherwise, you can also modify the open source template in the repo to fit your needs.

I hope this helps,
Michael
